language: bash
services: docker

env:
    - IMAGE=vapoursynth
    - VERSION=R35
    - VERSION=R35 VARIANT=plugins
    - VERSION=R36
    - VERSION=R36 VARIANT=plugins
    
install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="$IMAGE:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - make VAPOURSYNTH_RELEASE=${VERSION} IMAGE=${image} all ${VARIANT}

after_script:
  - docker images
    
# vim:set et ts=2 sw=2:
