sudo: required

env:
  global:
      - secure: PLDpwZpbdt35/L4mYN8QnN/E3LGcndGo7JwCL3s03UiIUWO6qq2FhZSVoJQSVwUibMK2HaQ3VPKPOH2VddU0D7HpgRvytqgj7+A0mNfD/7xSR9wosHX8a6WyTZn0VCi/2Li8QiXTDoAO46Qgo3XmHvrfG1JwOnChw+WDkv21RH0zpddHTs/1vp0/B6K3KHWWB9F1Tq18Le8HynaovOFnyCIHe2s4/FUiz4wqa4pzVlt5c9kezpx008psoTXEjueyGirLL8Ms0DfPM9F1mSHlNs9j0+WMUARsLCTlanor4ODs4xNGTJW4W257fhNjz3u658MFvJqzDMM7iMTwQIopfEIPuFf5EEXbezHK+fh98GxPRPktDzOds06InRwImeSgEXKtMQSU6bdVHD/OMgRa+WsqBpyY20Jaiy7T91mVCSE/kEX++pxPpSexnbk3tCTpB+RP+lu3fhx1r+ez3VZ4/70rdjb8c7X01iqjIhlImmsp3MEfqQHIQx0RbCOayRi7V+D3KB0CX0uJzRIqDnIWipfEutK99UFiEJLIwgSpQcwpjy+Zx/6fPTO8wZAkif/NdnK563MPVl31Ok/Akit4H6CCng1a9qYpsFsgP6juaGw3dU4pjvQKmulcm7JuY55b8TNw8cDOLm27ByY/scoTbzunRbDsqR0KCieJbZ7TKYE=
      - secure: A3PbD0zrnDmiH1BsWno6p1v14aHnVu3OmZSMSDy+VvwvSPpYiNZPiepO4Ii1Wd6DGApjQwktvvjIk60UOfwhy6rRgtNo8mrpsobnvpqg3to8t50iaTPkkqUCEv3UxE1hgf1pmQ3Oq8QxnCWIe62A91yi7Zym8VzH7VLGXEfn6an/EVN0oMNKJL2zGpZHOWDI5BDWdPG/Lv2Go5yj4KF3bveZG3NbHekjpuwU/TgJMISRZtYn/CyxRoZUl1MfUCfBc83VNLnUqnF+3eFoo3P/RktmOxSzQvsDNQaz51fTD/mWsgk9psiFxd/UdrEt3OHIpIW05B2DQpSESVSvO0hDkererwp4lMbqJMewHHTZGTjB0UHnw0CpSWmueUO+DNqTt5TS8GGryfPQfERSsM1rB7VbfQEI0c38F2v027Lj7bRx/bV7T4N6nh9e7Pk5RAvOEtvkZInBVjAvEIipHkiKlfRkxxEN3hZ0FcdkkEtCN1eLlNb9jeIXvq98n3IuAkzUd+ZutW93IwGPGC+MSAJUGgcW8Fxx45QmZjZ7zbTtN5vTySb0tcZ9Rbu2iJU8HhoPOkM4CwOyX7c8qhxPy14dyhuXZlnE5cM1hW/zkdO8ZKtOutKF4EgeSmOftl/LqnfLc0iXJHT9aQ/G2DcL/Yj6FdWfah2g1CKgbl0qajKy9PE=
      - COMMIT=${TRAVIS_COMMIT::8} 
      - IMAGE=vapoursynth
    
services:
    - docker

script:
    - make all IMAGE=$IMAGE

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=$DOCKER_USER/$IMAGE
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - echo $REPO:$TAG:$COMMIT
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
    - make clean
