language: bash
services: docker

env:
    - VERSION=R35
    - VERSION=R36
    
install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="vapoursynth:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - make VAPOURSYNTH_RELEASE=${VERSION} IMAGE=${image} all ${VARIANT}

after_script:
  - docker images
    
# vim:set et ts=2 sw=2:
